# Generated by Django 3.1.7 on 2021-06-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_auto_20210630_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='slug',
            field=models.SlugField(default=3),
            preserve_default=False,
        ),
    ]
