# Generated by Django 3.1.7 on 2021-06-10 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_auto_20210609_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='detail',
            field=models.CharField(max_length=260),
        ),
    ]
