# Generated by Django 3.1.7 on 2021-07-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0009_auto_20210701_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='slug',
        ),
    ]
