# Generated by Django 3.1.7 on 2021-06-09 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='contact',
            field=models.TextField(default=23.49),
            preserve_default=False,
        ),
    ]
